# Generated by Django 5.0 on 2026-01-05 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='owner_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('RABBIT', 'Rabbit'), ('OTHER', 'Other')], default='DOG', max_length=10)),
                ('breed', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, help_text="Tell us about your pet's personality")),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('last_vaccination_date', models.DateField(blank=True, null=True)),
                ('health_issues', models.TextField(blank=True, help_text='Any health concerns or special needs')),
                ('is_neutered', models.BooleanField(default=False)),
                ('is_available_for_mating', models.BooleanField(default=True)),
                ('preferred_breed', models.CharField(blank=True, help_text='Preferred breed for mating', max_length=100)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('RABIES', 'Rabies'), ('DHPP', 'DHPP (Distemper, Hepatitis, Parainfluenza, Parvovirus)'), ('BORDETELLA', 'Bordetella (Kennel Cough)'), ('LYME', 'Lyme Disease'), ('FVRCP', 'FVRCP (Feline Viral Rhinotracheitis, Calicivirus, Panleukopenia)'), ('FELV', 'FeLV (Feline Leukemia)'), ('OTHER', 'Other')], max_length=20)),
                ('vaccine_name', models.CharField(blank=True, max_length=100)),
                ('date_administered', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('veterinarian_name', models.CharField(blank=True, max_length=100)),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='vaccination_certificates/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.pet')),
            ],
            options={
                'ordering': ['-date_administered'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Message from requester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_matches', to='pets.pet')),
                ('to_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_matches', to='pets.pet')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('from_pet', 'to_pet')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pets.pet')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'pet')},
            },
        ),
    ]
